config/routes.rb
Buddylist::Application.routes.draw do

  root to: "dashboard#index"

  devise_for :users


  # Users
  get     'users/search(.format)' => 'users#search',                      as: :search_user
  get     'users/:user_id(.:format)' => 'users#view',                     as: :user
  get     'users/:user_id/friends(.:format)' => 'users#search_friends',   as: :user_friends

  # Posts
  post    'status/create' => 'statusPosts#create',                        as: :create_status_post
  get     'status/:post_id(.:format)' => 'statusPosts#view',              as: :status_post
  delete  'status/:post_id/destroy(.:format)' => 'statusPosts#destroy',   as: :destroy_status_post

  # Videos
  post    'videos/create' => 'videoPosts#create',                         as: :create_video_post
  get     'videos/:video_id(.:format)' => 'videoPosts#view',              as: :video_post
  delete  'videos/:video_id/destroy(.:format)' => 'videoPosts#destroy',   as: :destroy_video_post

  # Comments
  post    'comments/create' => 'comments#create',                         as: :create_comment
  get     'comments/:comment_id(.:format)' => 'comments#view',            as: :comment
  delete  'comments/:comment_id/destroy' => 'comments#destroy',           as: :destroy_comment

  # Likes
  post    'likes/create' => 'likes#create',                               as: :create_like
  delete  'likes/destroy/:likable_id' => 'likes#destroy',                 as: :destroy_like

  # Relationships
  post    'relationships/create_friend/:user_id' => 'relationships#create_friend',      as: :create_friend
  delete  'relationships/destroy_friend/:user_id' => 'relationships#destroy_friend',    as: :destroy_friend
  get     'relationships/friend_requests' => 'relationships#friend_requests',           as: :friend_requests

  # Newsfeeds
  get     'newsfeed' => 'newsfeeds#view',                                 as: :newsfeed

  # Notifications
  get     'notifications/' => 'notifications#index',                              as: :notifications
  delete  'notifications/' => 'notifications#destroy',                            as: :destroy_notification

  # Albums
  get     'users/:user_id/albums' => 'albums#index',                      as: :albums
  get     'users/:user_id/albums/new' => 'albums#new',                    as: :new_album
  post    'albums/create' => 'albums#create',                             as: :create_album
  get     'albums/:album_id' => 'albums#view',                            as: :album
  delete  'albums/:album_id/delete' => 'albums#destroy',                  as: :destroy_album

  # Photos
  get     'photos/:photo_id' => 'photos#view',                            as: :photo
  get     'albums/:album_id/photos/new' => 'photos#new',                  as: :new_photo
  post    'photos/create' => 'photos#create',                             as: :create_photo
  delete  'photos/:photo_id/destroy' => 'photos#destroy',                 as: :destroy_photo
  get     'photos/:photo_id/set_profile' => 'photos#set_profile',         as: :set_profile_photo



  # Misc. tests
  get 'test/:action' => 'test#'

end

app/models/video_post.rb
class VideoPost  < Post

  # Used for reg exp link_url
  IPV4_PART = /\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]/  # 0-255
  ALNUM = "a".match(/[[:alnum:]]/) ? /[[:alnum:]]/ : /[^\W_]/

  # Properties
  field :link_url, type: String
  field :description, type: String


  # Validation
  validates_presence_of :link_url
  validates_format_of :link_url, with: %r{
    \A
    https?://                                                          # http:// or https://
    ([^\s:@]+:[^\s:@]*@)?                                              # optional username:pw@
    ( ((#{ALNUM}+\.)*xn--)?#{ALNUM}+([-.]#{ALNUM}+)*\.[a-z]{2,6}\.? |  # domain (including Punycode/IDN)...
        #{IPV4_PART}(\.#{IPV4_PART}){3} )                              # or IPv4
    (:\d{1,5})?                                                        # optional port
    ([/?]\S*)?                                                         # optional /whatever or ?whatever
    \Z
    }iux

end

app/controllers/video_posts_controller.rb
class VideoPostsController < ApplicationController

  before_filter :authenticate_user!

  def view
    videopost = VideoPost.find params[:video_id]

    authorize! :view, videopost

    respond_to do |format|
      format.html { render locals: { videopost: videopost } }
      format.json { render json: videopost }
    end

  end

  def create
    receiver = User.find params[:receiver_id]

    authorize! :create_video_posts, receiver

    # VideoPost
    @video_post             = VideoPost.new params[:video_post]
    @video_post.created_by  = current_user
    @video_post.created_for = receiver

    if @video_post.valid? && @video_post.save!
      redirect_to_back video_post_path @video_post
    else
      render action: :new, locals: { receiver: receiver }
    end

  end

  def destroy
    videopost = VideoPost.find params[:video_id]

    authorize! :destroy, videopost

    videopost.delete

    respond_to do |format|
      format.html { redirect_to_back user_url videopost.created_by }
      format.json { render json: "deleted" }
    end
  end

  def new

  end
end

app/helpers/video_posts_helper.rb
module VideoPostsHelper

  def determine_video_resource video_url
    # example video_url: http://www.youtube.com
    if video_url.match /^https?:\/\/(www\.)?youtube\.com/i
      _link = video_url.gsub /watch\?v=/, 'embed/'
      return _link.gsub /&[a-zA-Z0-9]/, ''
    elsif video_url.match /^https?:\/\/(www\.)?vimeo\.com/i
      # vimeo
    end

  end

  def get_code_video video_url
     return video_url.gsub /http:\/\/www.youtube.com\/watch\?v=([a-z0-9])&/i, '\\1'
  end

end

app/views/video_posts/_new.html.haml
= form_for (@video_post ||= VideoPost.new), url: create_video_post_url do |form|

  = render partial: "layouts/common/validation_errors", locals: { model: @video_post }

  = hidden_field_tag :receiver_id, receiver.id

  .uiTextInputWrapper.small
    .input.large.post-description
      = form.text_area :link_url, placeholder: "video url", class: :autogrow
    .input.large.post-description
      = form.text_area :description, placeholder: "What's keeping you busy?", class: :autogrow
    .input.tag_users.with-label.hidden
      %label With
      = text_area_tag :tagged_users, nil, placeholder: "With…", class: "token-input", "data-source" => user_friends_url(current_user)
    .controls.show-on-focus
      %ul.menu
        %li{ "data-toggle" => ".input.tag_users"}
          %span.icon.small.tag-user
      = form.submit "Share", class: [:uiButton, :uiButtonConfirm]
%br

app/views/video_posts/_video_post.html.haml
.post.status-post.commentable.likable

  - if can? :destroy, post
    %a{ href: destroy_video_post_url(post), class: [:destroy], "data-method" => "delete", "data-confirm" => "Are you sure you want to delete this video?"}
      %span.icon.small.destroy-post

  = user_picture post.created_by, :medium

  %p.author
    - unless post.created_by == post.created_for
      #{link_to_author post.created_by}
      %span.to ►
    #{link_to_author post.created_for}

    - unless (tagged_users = format_tagged_users(post)).blank?
      = simple_format post.description + tagged_users, class: :description, sanitize: false
    - else
      = simple_format post.description, class: :description, sanitize: false

    =render partial: "video_posts/video_post_small", locals: {videopost: post}


  %ul.menu.reactions-menu
    %li.date-created
      #{time_ago_in_words post.created_at} ago

    - if can? :create_like, post
      %li
        = render partial: "likables/likable", locals: { likable: post }

    - if can? :create_comment, post
      %li
        %button.uiLink.add-comment Comment

  .reactions
    - unless (liking_users = format_liking_users(post)).blank?
      .liking-users
        %span.icon.small.like
        = liking_users

    = render partial: "commentable/commentable", locals: { commentable: post }

app/views/video_posts/_video_post_small.html.haml
%a{ href: "#info", rel: "facebox" }
  %img{ src: "http://img.youtube.com/vi/" + get_code_video(videopost.link_url) +  "/1.jpg" }

%div#info{ style: "display: none" }
  %iframe{ width: 560, height: "315", src: determine_video_resource(videopost.link_url) }

app/views/video_posts/_view_video.html.haml
testing!

app/views/video_posts/new.html.haml
.island

  = render partial: "video_posts/new", locals: { receiver: receiver }

app/views/video_posts/view.html.haml
.island

  %h1 Video

  -#= render partial: "video_posts/view_video", locals: { post: videopost }