config/routes.rb
Buddylist::Application.routes.draw do

  root to: "dashboard#index"

  devise_for :users


  # Users
  get     'users/search(.format)' => 'users#search',                      as: :search_user
  get     'users/:user_id(.:format)' => 'users#view',                     as: :user
  get     'users/:user_id/friends(.:format)' => 'users#search_friends',   as: :user_friends

  # Posts
  post    'status/create' => 'statusPosts#create',                        as: :create_status_post
  get     'status/:post_id(.:format)' => 'statusPosts#view',              as: :status_post
  delete  'status/:post_id/destroy(.:format)' => 'statusPosts#destroy',   as: :destroy_status_post

  # Videos
  post    'videos/create' => 'videoPosts#create',                         as: :create_video_post
  get     'videos/:video_id(.:format)' => 'videoPosts#view',              as: :video_post
  delete  'videos/:video_id/destroy(.:format)' => 'videoPosts#destroy',   as: :destroy_video_post

  # Comments
  post    'comments/create' => 'comments#create',                         as: :create_comment
  get     'comments/:comment_id(.:format)' => 'comments#view',            as: :comment
  delete  'comments/:comment_id/destroy' => 'comments#destroy',           as: :destroy_comment

  # Likes
  post    'likes/create' => 'likes#create',                               as: :create_like
  delete  'likes/destroy/:likable_id' => 'likes#destroy',                 as: :destroy_like

  # Relationships
  post    'relationships/create_friend/:user_id' => 'relationships#create_friend',      as: :create_friend
  delete  'relationships/destroy_friend/:user_id' => 'relationships#destroy_friend',    as: :destroy_friend
  get     'relationships/friend_requests' => 'relationships#friend_requests',           as: :friend_requests

  # Newsfeeds
  get     'newsfeed' => 'newsfeeds#view',                                 as: :newsfeed

  # Notifications
  get     'notifications/' => 'notifications#index',                              as: :notifications
  delete  'notifications/' => 'notifications#destroy',                            as: :destroy_notification

  # Albums
  get     'users/:user_id/albums' => 'albums#index',                      as: :albums
  get     'users/:user_id/albums/new' => 'albums#new',                    as: :new_album
  post    'albums/create' => 'albums#create',                             as: :create_album
  get     'albums/:album_id' => 'albums#view',                            as: :album
  delete  'albums/:album_id/delete' => 'albums#destroy',                  as: :destroy_album

  # Photos
  get     'photos/:photo_id' => 'photos#view',                            as: :photo
  get     'albums/:album_id/photos/new' => 'photos#new',                  as: :new_photo
  post    'photos/create' => 'photos#create',                             as: :create_photo
  delete  'photos/:photo_id/destroy' => 'photos#destroy',                 as: :destroy_photo
  get     'photos/:photo_id/set_profile' => 'photos#set_profile',         as: :set_profile_photo



  # Misc. tests
  get 'test/:action' => 'test#'

end

app/models/comment.rb
class Comment

  include Mongoid::Document
  include Mongoid::Timestamps

  # Associations
  include Likable
  include UserTaggable
  belongs_to :commentable, polymorphic: true
  belongs_to :created_by, class_name: "User"

  # Validation
  validates_presence_of :message

  # Properties
  field :message, type: String

end

app/controllers/comments_controller.rb
# Comment Controller
#
# Creates, displays and destroys Comments (on Commentables).
#
# @see Comment
# @see Commentable
# @see UserTag
# @see UserTaggable
#
class CommentsController < ApplicationController

  # Require an authenticated user
  before_filter :authenticate_user!


  # View a comment
  #
  # Redirects to the commentable's path, so the comment can be viewed in proper context.
  #
  def view
    comment = Comment.find params[:comment_id]

    authorize! :view, comment

    redirect_to polymorphic_path comment.commentable
  end


  # Create a Comment on a Commentable
  #
  def create
    commentable = retrieve_commentable

    authorize! :create_comment, commentable

    # Create the comment
    @comment             = Comment.new params[:comment]
    @comment.created_by  = current_user
    @comment.commentable = commentable


    if @comment.valid? && @comment.save
      # Create user tags (if provided)
      params[:tagged_users].split(",").each do |user_id|
        @comment.user_tags.create! user_id: user_id
      end

      # Redirect back, or to the commentable's url
      redirect_to_back polymorphic_path @comment.commentable
    else
      # Display the create comment form
      render action: :new, locals: { commentable: @comment.commentable }
    end
  end


  # Destroy a comment
  #
  def destroy
    comment = Comment.find params[:comment_id]

    authorize! :destroy, comment

    comment.delete

    redirect_to_back polymorphic_path comment.commentable
  end


  private


  # Display the form for creating new comments.
  #
  def new

  end


  # Retrieve the commentable based on the provided type and id.
  #
  # @return [Commentable] The commentable the comment is related with.
  #
  def retrieve_commentable
    collection = Object::const_get params[:commentable_type]

    unless collection.include? Commentable
      raise "Can't comment on this type of post."
    end

    commentable = collection.find params[:commentable_id]

    authorize! :view, commentable

    commentable
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
- if can? :view, comment
  .comment

    - if can? :destroy, comment
      %a{ href: destroy_comment_url(comment), class: :destroy, "data-method" => "delete", "data-confirm" => "Are you sure you want to delete this comment?"}
        %span.icon.small.destroy-post

    = user_photo comment.created_by, :small

    %p.author
      = link_to_author comment.created_by

    - unless (tagged_users = format_tagged_users(comment)).blank?
      = simple_format comment.message + tagged_users, class: :description, sanitize: false
    - else
      = simple_format comment.message, class: :description, sanitize: false

    %ul.menu
      %li.date-created
        #{time_ago_in_words comment.created_at} ago
      - if can? :create_like, comment
        %li
          = render partial: 'likables/likable', locals: { likable: comment }
      - unless (liking_users = format_liking_users(comment)).blank?
        %li.liking-users
          = liking_users

app/views/comments/_new.html.haml
-# TODO attempt Comment.new(commentable: commentable) with form.hidden_field instead of tags.

= form_for (@comment ||= Comment.new), url: create_comment_url do |form|

  = hidden_field_tag :commentable_id, commentable.id
  = hidden_field_tag :commentable_type, commentable.class.name

  = render partial: "layouts/common/validation_errors", locals: { model: @comment }

  = user_photo current_user, :small

  .uiTextInputWrapper.small
    .input.comment-message
      = form.text_area :message, { placeholder: "Write comment…", class: :autogrow }
    .input.tag_users.with-label.hidden
      %label With
      = text_area_tag :tagged_users, nil, placeholder: "With…", class: "token-input", "data-source" => user_friends_url(current_user)
    .controls.show-on-focus
      %ul.menu
        %li{ "data-toggle" => ".input.tag_users"}
          %span.icon.small.tag-user
      = form.submit "Add Comment", class: [:uiButton, :uiButtonConfirm]

app/views/comments/new.html.haml
.island

  = render partial: commentable, as: :post