config/routes.rb
Buddylist::Application.routes.draw do

  root to: "dashboard#index"

  devise_for :users


  # Users
  get     'users/search(.format)' => 'users#search',                      as: :search_user
  get     'users/:user_id(.:format)' => 'users#view',                     as: :user
  get     'users/:user_id/friends(.:format)' => 'users#search_friends',   as: :user_friends

  # Posts
  post    'status/create' => 'statusPosts#create',                        as: :create_status_post
  get     'status/:post_id(.:format)' => 'statusPosts#view',              as: :status_post
  delete  'status/:post_id/destroy(.:format)' => 'statusPosts#destroy',   as: :destroy_status_post

  # Videos
  post    'videos/create' => 'videoPosts#create',                         as: :create_video_post
  get     'videos/:video_id(.:format)' => 'videoPosts#view',              as: :video_post
  delete  'videos/:video_id/destroy(.:format)' => 'videoPosts#destroy',   as: :destroy_video_post

  # Comments
  post    'comments/create' => 'comments#create',                         as: :create_comment
  get     'comments/:comment_id(.:format)' => 'comments#view',            as: :comment
  delete  'comments/:comment_id/destroy' => 'comments#destroy',           as: :destroy_comment

  # Likes
  post    'likes/create' => 'likes#create',                               as: :create_like
  delete  'likes/destroy/:likable_id' => 'likes#destroy',                 as: :destroy_like

  # Relationships
  post    'relationships/create_friend/:user_id' => 'relationships#create_friend',      as: :create_friend
  delete  'relationships/destroy_friend/:user_id' => 'relationships#destroy_friend',    as: :destroy_friend
  get     'relationships/friend_requests' => 'relationships#friend_requests',           as: :friend_requests

  # Newsfeeds
  get     'newsfeed' => 'newsfeeds#view',                                 as: :newsfeed

  # Notifications
  get     'notifications/' => 'notifications#index',                              as: :notifications
  delete  'notifications/' => 'notifications#destroy',                            as: :destroy_notification

  # Albums
  get     'users/:user_id/albums' => 'albums#index',                      as: :albums
  get     'users/:user_id/albums/new' => 'albums#new',                    as: :new_album
  post    'albums/create' => 'albums#create',                             as: :create_album
  get     'albums/:album_id' => 'albums#view',                            as: :album
  delete  'albums/:album_id/delete' => 'albums#destroy',                  as: :destroy_album

  # Photos
  get     'photos/:photo_id' => 'photos#view',                            as: :photo
  get     'albums/:album_id/photos/new' => 'photos#new',                  as: :new_photo
  post    'photos/create' => 'photos#create',                             as: :create_photo
  delete  'photos/:photo_id/destroy' => 'photos#destroy',                 as: :destroy_photo
  get     'photos/:photo_id/set_profile' => 'photos#set_profile',         as: :set_profile_photo



  # Misc. tests
  get 'test/:action' => 'test#'

end

app/models/notification.rb
class Notification

  include Mongoid::Document
  include Mongoid::Timestamps

  # Association (receiver of notification)
  belongs_to :user

  # Fields
  field :read_status, type: Boolean, default: false

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :authenticate_user!

  after_filter :update_read_status


  # Show list of notifications
  def index
    notifications = current_user.notifications
    unread_notifications = current_user.unread_notifications.size

    respond_to do |format|
      format.html { render locals: { notifications: notifications, unread_notifications: unread_notifications }}
    end
  end

  def destroy
    current_user.notifications.destroy_all

    redirect_to :notifications
  end

  private

  def update_read_status
    current_user.notifications.update_all(
            read_status: true
    )
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper


  def determine_liked_type likable

    if likable.instance_of? StatusPost

      link = link_to likable.description, status_post_url(likable)
      raw "status " + link

    elsif likable.instance_of? PhotoPost

      link = link_to likable.description, photo_post_url(likable)
      raw " photo " + link

    elsif likable.instance_of? Comment

      link = link_to likable.message, status_post_url(likable.commentable)
      raw " comment " + link

    end

  end


end

app/views/notifications/_comment_notification.html.haml
= link_to notification.comment.created_by.name, user_url(notification.comment.created_by)
commented on the status
= link_to notification.comment.commentable.description, status_post_url(notification.comment.commentable)

app/views/notifications/_like_notification.html.haml
= link_to notification.author.name, user_url(notification.author)
likes your
= determine_liked_type notification.like

app/views/notifications/_sidebar.html.haml
.person-sidebar

  %h2 Sort by

  %ul
    %li
      = link_to "Comments", sort_notifications_by_url("comments")
    %li
      = link_to "Statusposts", sort_notifications_by_url("status_posts")
    %li
      = link_to "Likes", sort_notifications_by_url("likes")

app/views/notifications/_status_post_notification.html.haml
= link_to notification.status_post.created_by.name, user_url(notification.status_post.created_by)
placed a status on
= link_to "your Wall.", status_post_url(notification.status_post)

app/views/notifications/index.html.haml
.island

  - unless notifications.size == 0
    %ul.top-controls.menu
      %li= link_to "Delete all notifications", destroy_notification_path, class: :uiButton, method: :delete


  %h1.border_bottom Your Notifications

  - unless notifications.size == 0

    - unless unread_notifications == 0
      %p
        You have
        =unread_notifications
        unread notifications.

    %ul.notifications
      - for notify in notifications do
        - if notify.read_status == true
          %li= render partial: "notifications/" + notify.class.to_s.underscore, locals: {notification: notify}
        - else
          %li.unread= render partial: "notifications/" + notify.class.to_s.underscore, locals: {notification: notify}
  - else
    %p You don't have any notifications to read.