config/routes.rb
Buddylist::Application.routes.draw do

  root to: "dashboard#index"

  devise_for :users


  # Users
  get     'users/search(.format)' => 'users#search',                      as: :search_user
  get     'users/:user_id(.:format)' => 'users#view',                     as: :user
  get     'users/:user_id/friends(.:format)' => 'users#search_friends',   as: :user_friends

  # Posts
  post    'status/create' => 'statusPosts#create',                        as: :create_status_post
  get     'status/:post_id(.:format)' => 'statusPosts#view',              as: :status_post
  delete  'status/:post_id/destroy(.:format)' => 'statusPosts#destroy',   as: :destroy_status_post

  # Videos
  post    'videos/create' => 'videoPosts#create',                         as: :create_video_post
  get     'videos/:video_id(.:format)' => 'videoPosts#view',              as: :video_post
  delete  'videos/:video_id/destroy(.:format)' => 'videoPosts#destroy',   as: :destroy_video_post

  # Comments
  post    'comments/create' => 'comments#create',                         as: :create_comment
  get     'comments/:comment_id(.:format)' => 'comments#view',            as: :comment
  delete  'comments/:comment_id/destroy' => 'comments#destroy',           as: :destroy_comment

  # Likes
  post    'likes/create' => 'likes#create',                               as: :create_like
  delete  'likes/destroy/:likable_id' => 'likes#destroy',                 as: :destroy_like

  # Relationships
  post    'relationships/create_friend/:user_id' => 'relationships#create_friend',      as: :create_friend
  delete  'relationships/destroy_friend/:user_id' => 'relationships#destroy_friend',    as: :destroy_friend
  get     'relationships/friend_requests' => 'relationships#friend_requests',           as: :friend_requests

  # Newsfeeds
  get     'newsfeed' => 'newsfeeds#view',                                 as: :newsfeed

  # Notifications
  get     'notifications/' => 'notifications#index',                              as: :notifications
  delete  'notifications/' => 'notifications#destroy',                            as: :destroy_notification

  # Albums
  get     'users/:user_id/albums' => 'albums#index',                      as: :albums
  get     'users/:user_id/albums/new' => 'albums#new',                    as: :new_album
  post    'albums/create' => 'albums#create',                             as: :create_album
  get     'albums/:album_id' => 'albums#view',                            as: :album
  delete  'albums/:album_id/delete' => 'albums#destroy',                  as: :destroy_album

  # Photos
  get     'photos/:photo_id' => 'photos#view',                            as: :photo
  get     'albums/:album_id/photos/new' => 'photos#new',                  as: :new_photo
  post    'photos/create' => 'photos#create',                             as: :create_photo
  delete  'photos/:photo_id/destroy' => 'photos#destroy',                 as: :destroy_photo
  get     'photos/:photo_id/set_profile' => 'photos#set_profile',         as: :set_profile_photo



  # Misc. tests
  get 'test/:action' => 'test#'

end

app/models/status_post.rb
class StatusPost < Post

  # Properties
  field :description, type: String

  # Validations
  validates_presence_of :description

end

app/controllers/status_posts_controller.rb
# Status Posts Controller
#
# Creates, displays and destroys StatusPosts (status updates).
#
# @see StatusPost
# @see Likable
# @see Like
# @see Commentable
# @see Comment
# @see UserTaggable
# @see UserTag
#
class StatusPostsController < ApplicationController

  # Require an authenticated user
  before_filter :authenticate_user!


  # View a StatusPost
  #
  def view
    post = StatusPost.find params[:post_id]

    authorize! :view, post

    respond_to do |format|
      format.html { render :locals => { :post => post } }
      format.json { render :json => post }
    end
  end


  # Create a StatusPost
  #
  def create
    user = User.find params[:receiver_id]

    authorize! :create_posts, user

    # Create the StatusPost
    @status_post             = StatusPost.new params[:status_post]
    @status_post.created_by  = current_user
    @status_post.created_for = user

    if @status_post.valid? && @status_post.save
      # Create user tags (if provided)
      params[:tagged_users].split(",").each do |user_id|
        user_tag = UserTag.new user_id: user_id

        if can? :create, user_tag
          @status_post.user_tags << user_tag
        end
      end

      # Redirect back, or to the status post url.
      redirect_to_back status_post_path @status_post
    else
      # Show the create StatusPost form
      render action: :new, locals: { receiver: @status_post.created_for }
    end
  end


  # Destroy a StatusPost
  #
  def destroy
    post = StatusPost.find params[:post_id]

    authorize! :destroy, post

    post.delete

    respond_to do |format|
      format.html {redirect_to_back user_url post.created_by}
      format.json { render :json => 'success' }
    end
  end


  protected


  # Display the create a StatusPost form
  #
  def new

  end


end

app/helpers/status_posts_helper.rb
module StatusPostsHelper
end

app/views/status_posts/_new.html.haml
= form_for (@status_post ||= StatusPost.new), url: create_status_post_url do |form|

  = render partial: "layouts/common/validation_errors", locals: { model: @status_post }

  = hidden_field_tag :receiver_id, receiver.id

  .uiTextInputWrapper.small
    .input.large.post-description
      = form.text_area :description, placeholder: "What's keeping you busy?", class: :autogrow
    .input.tag_users.with-label.hidden
      %label With
      = text_area_tag :tagged_users, nil, placeholder: "With…", class: "token-input", "data-source" => user_friends_url(current_user)
    .controls.show-on-focus
      %ul.menu
        %li{ "data-toggle" => ".input.tag_users"}
          %span.icon.small.tag-user
      = form.submit "Share", class: [:uiButton, :uiButtonConfirm]
%br

app/views/status_posts/_status_post.html.haml
.post.status-post.commentable.likable

  - if can? :destroy, post
    %a{ href: destroy_status_post_url(post), class: [:destroy], "data-method" => "delete", "data-confirm" => "Are you sure you want to delete this post?"}
      %span.icon.small.destroy-post

  = user_photo post.created_by, :medium

  %p.author
    - unless post.created_by == post.created_for
      #{link_to_author post.created_by}
      %span.to ►
    #{link_to_author post.created_for}

    - unless (tagged_users = format_tagged_users(post)).blank?
      = simple_format post.description + tagged_users, class: :description, sanitize: false
    - else
      = simple_format post.description, class: :description, sanitize: false

  %ul.menu.reactions-menu
    %li.date-created
      #{time_ago_in_words post.created_at} ago

    - if can? :create_like, post
      %li
        = render partial: "likables/likable", locals: { likable: post }

    - if can? :create_comment, post
      %li
        %button.uiLink.add-comment Comment

  .reactions
    - unless (liking_users = format_liking_users(post)).blank?
      .liking-users
        %span.icon.small.like
        = liking_users

    = render partial: "commentable/commentable", locals: { commentable: post }

app/views/status_posts/new.html.haml
.island

  = render partial: "status_posts/new", locals: { receiver: receiver }

app/views/status_posts/view.html.haml
.island

  %h1 Status

  = render partial: "status_posts/status_post", locals: { post: post }